### ISSUE TITLE
API popup 1 of 3

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/coloradohome.ai#1]
@codextiny

[https://coloradohome.ai/home/](url)

U: [support@homeowner.ai](mailto:support@homeowner.ai)
pw:M!l3st0nesL@bs

Please add API pop up to:

Get Started in header
Search bar in hero image (please make button the secondary color)
Get Started button in CTA prefooter section

**Comment by shannonbaldwin** [comment]
@codextiny 

Search bar not working. 

![image](https://github.com/user-attachments/assets/aae01c80-4272-4cfa-a449-6728e6729add)

**Comment by shannonbaldwin** [comment]
@codextiny 
Please update the radius on the button in pop-up to the same border radius as get started button in header. 

<img width="420" alt="image" src="https://github.com/user-attachments/assets/82c5306f-3743-43fa-a0c3-ff6a302ca8e5" />

**Comment by codextiny** [comment]
> @codextiny
> 
> Search bar not working.
> 
> ![image](https://private-user-images.githubusercontent.com/167017886/398227579-aae01c80-4272-4cfa-a449-6728e6729add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5ODgyNjcsIm5iZiI6MTczNDk4Nzk2NywicGF0aCI6Ii8xNjcwMTc4ODYvMzk4MjI3NTc5LWFhZTAxYzgwLTQyNzItNGNmYS1hNDQ5LTY3MjhlNjcyOWFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QyMTA2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODMyOGJiMTkzYzJlN2Q3NTU5Yzk3YTI5ZTg4MmFmMGM0NTM3Nzc3NjUzNTZhMWI0YTZlYjQ1ZDU0NzIzYWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ezd9yufvCSctIFKoZYaxwjIkG8JeimDNEsbLiNCmQ6k)

search bar is working but search bar's padding was not correct so it seems like not working, adjusted padding and height .

@shannonbaldwin

**Comment by codextiny** [comment]
> @codextiny Please update the radius on the button in pop-up to the same border radius as get started button in header.
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/167017886/398256003-82c5306f-3743-43fa-a0c3-ff6a302ca8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5ODgyNjcsIm5iZiI6MTczNDk4Nzk2NywicGF0aCI6Ii8xNjcwMTc4ODYvMzk4MjU2MDAzLTgyYzUzMDZmLTM3NDMtNDNmYS1hMGMzLWZmNmEzMDJjYThlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QyMTA2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjNmMDY2Njc4YmY5ODRjOTAyODc5MzFhNjhjYmUzMzQ1MTEzOTZhY2VhYjA0NTAxMmM3NjQxOTE1ODJkYWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EbSOaQjfAHK62JBwLw88PXBsLiwtg9pI5Tg8VRZ3n5k">

done from our side .

@shannonbaldwin
